# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caa282fda1749c277faf3b19cc3e51b1821068e1642900a75e30b9e3383c38bc776b5e8180ec74b421bac0a93e5ac8441be5867153a1a23ec56103bdb5bd28a9

test:
  secret_key_base: ebd4229eacb305d6a01a439f0174aa2429afab473ae5c15bcca759e8662470bde43c37866d898094e752755da172fb813bd32e3d295641cf93e87dda0dcea4b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
